bmi: src/print_results/bmi/bmi.h File Reference
bmi.h File Reference
#include <assert.h>
#include <stdbool.h>
#include "is_valid_sex/is_valid_sex.h"
Functions
float bmi (float height, float weight)
const char * corporature (float height, float weight, char sex)
float overweight (float height, float weight, char sex)
float underweight (float height, float weight, char sex)
Function Documentation
float bmi (float height, float weight)
Calcola l'indice di massa corporea
Parameters
height
weight
Returns
Definition at line 25 of file bmi.c.
const char* corporature (float height, float weight, char sex)
Calcola se il soggetto è in sovrappeso, in normopeso o in sottopeso
Precondition
il carattere del sesso deve essere un F o una M
Parameters
height
weight
sex
Returns
Definition at line 47 of file bmi.c.
References is_valid_sex().
float overweight (float height, float weight, char sex)
Calcola l'entità del sovrappeso
Precondition
il carattere del sesso deve essere un F o una M
l'indice di massa corporea deve essere maggiore di 24 per gli uomini e maggiore di 22 per le donne
Parameters
height
weight
sex
Returns
Definition at line 63 of file bmi.c.
References is_valid_sex().
float underweight (float height, float weight, char sex)
Calcola l'entità del sottopeso
Precondition
il carattere del sesso deve essere un F o una M
l'indice di massa corporea deve essere minore di 20 per gli uomini e minore di 18 per le donne
Parameters
height
weight
sex
Returns
Definition at line 79 of file bmi.c.
References is_valid_sex().