bmi: src/is_valid_sex/is_valid_sex.h File Reference
is_valid_sex.h File Reference
#include <stdbool.h>
Functions
bool is_valid_sex (char sex)
Function Documentation
bool is_valid_sex (char sex)
Verifica che il carattere che identifica il sesso sia una M o una F
Parameters
sex
Returns
Definition at line 13 of file is_valid_sex.c.
Referenced by corporature(), get_sex(), overweight(), and underweight().